import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#a98fff',
        'on-tertiary-fixed': '#380014',
        'surface-container-lowest': '#000000',
        'error-container': '#a70138',
        'surface-bright': '#2c2b33',
        'on-error': '#490013',
        'on-tertiary': '#48001c',
        'on-primary': '#340090',
        'on-tertiary-container': '#100003',
        'primary-fixed': '#a98fff',
        'tertiary-fixed-dim': '#ff769b',
        'primary': '#b6a0ff',
        'inverse-surface': '#fbf8ff',
        'on-secondary': '#004d57',
        'secondary-fixed-dim': '#00d7f0',
        'on-background': '#f8f5fd',
        'secondary-fixed': '#26e6ff',
        'inverse-primary': '#6834eb',
        'on-primary-container': '#280072',
        'surface-dim': '#0e0e13',
        'surface-container-highest': '#25252c',
        'tertiary-fixed': '#ff8fa9',
        'surface': '#0e0e13',
        'tertiary-container': '#fd3e80',
        'surface-variant': '#25252c',
        'outline-variant': '#48474d',
        'secondary-dim': '#00d4ec',
        'surface-container': '#19191f',
        'on-primary-fixed': '#000000',
        'on-secondary-fixed-variant': '#005964',
        'on-tertiary-fixed-variant': '#770033',
        'on-surface-variant': '#acaab1',
        'outline': '#76747b',
        'inverse-on-surface': '#55545a',
        'surface-container-high': '#1f1f26',
        'on-primary-fixed-variant': '#32008a',
        'secondary-container': '#006875',
        'on-surface': '#f8f5fd',
        'tertiary': '#ff6c95',
        'primary-fixed-dim': '#9c7eff',
        'error': '#ff6e84',
        'background': '#0e0e13',
        'tertiary-dim': '#ff6c95',
        'surface-container-low': '#131318',
        'on-secondary-container': '#e8fbff',
        'secondary': '#00e3fd',
        'error-dim': '#d73357',
        'primary-dim': '#7e51ff',
        'on-error-container': '#ffb2b9',
        'on-secondary-fixed': '#003a42',
        'surface-tint': '#b6a0ff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
} satisfies Config;
