ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS last_bot_action TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS active_flow TEXT,
  ADD COLUMN IF NOT EXISTS winback_sent BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS telegram_user_id TEXT;
